name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout source code
    - name: Checkout repository
      uses: actions/checkout@v4


    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.X'   # match your project version

    # 3. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./RetServices/RetServices.sln

    # 4. Build solution
    - name: Build
      run: dotnet build ./RetServices/RetServices.sln --no-restore --configuration Release

    # 5. Run unit tests
    - name: Run API Tests
      run: dotnet test ./RetServices/test/API/API.Test/Base.API.Tests.csproj --configuration Release --logger "trx;LogFileName=api_test_results.trx" --verbosity normal

    - name: Run Application Tests
      run: dotnet test ./RetServices/test/Core/Base.Application.test/Base.Application.test.csproj --configuration Release --logger "trx;LogFileName=app_test_results.trx" --verbosity normal

    #6.Uplodaing the report
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'

    #7
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xUnit Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx



   
